stages:
  - setup
  - test
  - run_app

before_script:
  - apt-get update -qy
  - command -v python3 || { apt-get install -y python3; }
  - pip3 install --upgrade pip
  - pip3 install pipenv
  - pipenv --version
  
setup:
  script:
    - pipenv run python setup.py install

test:
  script:
    - pipenv run python -m pytest tests/

run_app:
  script:
    - pipenv run python your_app_script.py
